name: 🐛 Bug Report
description: Report something that isn't working right
title: "[Bug]: "
labels: [🐛 bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the form below so we can help quickly.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug clearly.
      description: Include what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, .NET version, browser, etc.
