name: ✨ Feature Request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: [💡 idea]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us understand your idea!

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: Why is this needed?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the ideal implementation.
